# steps:
#   steps:
#   # Build docker image
#   - name: 'gcr.io/cloud-builders/docker'
#     args: ['build', '-t', 'gcr.io/your-project/your-image:latest', '.']
#     dir: 'path/to/your/repository'
#   # Push docker image
#   - name: 'gcr.io/cloud-builders/docker'
#     args: ['push', 'gcr.io/your-project/your-image:latest']
#   # Copy DAG file in the appropriate bucket
#   - name: 'gcr.io/cloud-builders/gsutil'
#     args: ['cp', 'platform/dags/*', 'gs://europe-central2-tmdb-compos-5a03652c-bucket/dags/']
  

steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    apt-get update && apt-get install -y python3-pip
    pip install git+https://github.com/barney11/tmdb-data-platform.git@main
  id: 'install-package'

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud functions deploy extract_data_function \
      --runtime python38 \
      --trigger-http \
      --entry-point extract_data_function \
      --source platform/scripts/ \
      --allow-unauthenticated
  id: 'deploy-data-extraction-function'

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud functions deploy migrate_data_function \
      --runtime python38 \
      --trigger-http \
      --entry-point migrate_data_function \
      --source platform/scripts/ \
      --allow-unauthenticated
  id: 'deploy-data-migration-function'

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud functions deploy transform_data_function \
      --runtime python38 \
      --trigger-http \
      --entry-point transform_data_function \
      --source platform/scripts/ \
      --allow-unauthenticated
  id: 'deploy-data-transformation-function'

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud workflows deploy tmdb-workflow --source platform/workflows/tmdb_data_workflow.yaml

options :
  logging: CLOUD_LOGGING_ONLY