steps:

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud functions deploy extract_data_function \
      --runtime python38 \
      --trigger-http \
      --entry-point extract_data_function \
      --source platform/ \
      --allow-unauthenticated
  id: 'deploy-data-extraction-function'

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud functions deploy migrate_data_function \
      --runtime python38 \
      --trigger-http \
      --entry-point migrate_data_function \
      --source platform/ \
      --allow-unauthenticated
  id: 'deploy-data-migration-function'

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud functions deploy transform_data_function \
      --runtime python38 \
      --trigger-http \
      --entry-point transform_data_function \
      --source platform/ \
      --allow-unauthenticated
  id: 'deploy-data-transformation-function'

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud workflows deploy tmdb-workflow --source platform/workflows/tmdb_data_workflow.yaml

options :
  logging: CLOUD_LOGGING_ONLY
